# Generated by Django 6.0.4 on 2026-05-07 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
                ('search_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('domain_authority', models.IntegerField(default=0)),
                ('is_new', models.BooleanField(default=True)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlinks', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('total_warnings', models.IntegerField(default=0)),
                ('passed_core_web_vitals', models.BooleanField(default=True)),
                ('last_crawled', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='dashboard.project')),
            ],
        ),
    ]
