# Generated by Django 6.0.4 on 2026-05-07 03:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='cls_value',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='fid_value',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='lcp_value',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='quick_recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='total_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backlink',
            name='anchor_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='difficulty',
            field=models.FloatField(default=0.5, help_text='0.0 (Easy) to 1.0 (Hard)'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='intent',
            field=models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('navigational', 'Navigational')], default='informational', max_length=20),
        ),
        migrations.AddField(
            model_name='keyword',
            name='trend',
            field=models.CharField(choices=[('up', 'Trending Up'), ('flat', 'Stable'), ('down', 'Trending Down')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backlink',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.CreateModel(
            name='AuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('passed', 'Passed')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='error', max_length=50)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dashboard.auditresult')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.URLField()),
                ('domain_rating', models.IntegerField(default=0)),
                ('organic_traffic', models.CharField(blank=True, max_length=50)),
                ('keywords_count', models.IntegerField(default=0)),
                ('backlinks_count', models.CharField(blank=True, max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='dashboard.project')),
            ],
        ),
    ]
