# Generated by Django 6.0.4 on 2026-05-12 22:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auditresult_cls_value_auditresult_fid_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('traffic_estimate', models.FloatField(default=0.0)),
                ('avg_rank', models.FloatField(default=0.0)),
                ('performance_score', models.IntegerField(default=0)),
                ('backlinks_count', models.IntegerField(default=0)),
                ('new_backlinks', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dashboard.project')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
